import { randOne } from "@project/shared/src/utils/Helper";
import type { INameGenerator } from "./scenarios/Scenarios";

const FamilyNames = [
   "Bao", // 鲍
   "Bi", // 毕
   "Bu", // 步
   "Cai", // 蔡
   "Cao", // 曹
   "Chen", // 陈
   "Cheng", // 程
   "Cui", // 崔
   "Deng", // 邓
   "Dian", // 典
   "Ding", // 丁
   "Dong", // 董
   "Du", // 杜
   "Fa", // 法
   "Fan", // 樊
   "Fei", // 费
   "Feng", // 冯
   "Fu", // 傅
   "Gan", // 甘
   "Gao", // 高
   "Ge", // 葛
   "Geng", // 耿
   "Gong", // 龚
   "Gu", // 顾
   "Guan", // 关
   "Guo", // 郭
   "Han", // 韩
   "He", // 何
   "Hou", // 侯
   "Hu", // 胡
   "Hua", // 华
   "Huan", // 桓
   "Huang", // 黄
   "Ji", // 纪
   "Jia", // 贾
   "Jian", // 简
   "Jiang", // 姜
   "Jiang", // 蒋
   "Jiao", // 焦
   "Jin", // 金
   "Ju", // 沮
   "Kan", // 阚
   "Kong", // 孔
   "Lai", // 来
   "Li", // 李
   "Liang", // 梁
   "Liao", // 廖
   "Ling", // 凌
   "Liu", // 刘
   "Lou", // 楼
   "Lu", // 卢
   "Lu", // 陆
   "Lu", // 鲁
   "Lu", // 吕
   "Luo", // 骆
   "Ma", // 马
   "Man", // 满
   "Meng", // 孟
   "Mi", // 糜
   "Ni", // 倪
   "Niu", // 牛
   "Pan", // 潘
   "Pang", // 庞
   "Pei", // 裴
   "Qian", // 牵
   "Qiao", // 桥
   "Qin", // 秦
   "Quan", // 全
   "Ren", // 任
   "Shen", // 沈
   "Shi", // 士
   "Shi", // 史
   "Sui", // 眭
   "Sun", // 孙
   "Tan", // 谭
   "Tao", // 陶
   "Tian", // 田
   "Wang", // 王
   "Wei", // 韦
   "Wei", // 卫
   "Wei", // 魏
   "Wen", // 温
   "Wen", // 文
   "Wu", // 吴
   "Xi", // 郤
   "Xiang", // 向
   "Xie", // 谢
   "Xin", // 辛
   "Xu", // 徐
   "Xu", // 许
   "Xue", // 薛
   "Xun", // 荀
   "Yan", // 严
   "Yan", // 阎
   "Yan", // 颜
   "Yang", // 杨
   "Yang", // 羊
   "Yi", // 伊
   "Yin", // 尹
   "Ying", // 应
   "Yu", // 于
   "Yu", // 虞
   "Yuan", // 袁
   "Yue", // 乐
   "Zang", // 臧
   "Zhang", // 张
   "Zhao", // 赵
   "Zheng", // 郑
   "Zhong", // 钟
   "Zhou", // 周
   "Zhu", // 朱
   "Zong", // 宗
   "Zou", // 邹
   "Zu", // 祖
   "Gongsun", // 公孙
   "Guanqiu", // 毌丘
   "Huangfu", // 皇甫
   "Shisun", // 士孙
   "Sima", // 司马
   "Taishi", // 太史
   "Xiahou", // 夏侯
   "Zhongli", // 钟离
   "Zhuge", // 诸葛
];

const MaleGivenNames = [
   "An", // 安
   "Ang", // 昂
   "Ba", // 霸
   "Bao", // 苞
   "Bei", // 备
   "Biao", // 彪
   "Biao", // 表
   "Bin", // 斌
   "Bu", // 布
   "Can", // 粲
   "Cang", // 仓
   "Cao", // 操
   "Ce", // 策
   "Chao", // 超
   "Chen", // 琛
   "Cheng", // 承
   "Chong", // 冲
   "Chong", // 宠
   "Chu", // 褚
   "Chun", // 纯
   "Ci", // 慈
   "Cong", // 琮
   "Dan", // 诞
   "Dao", // 到
   "De", // 德
   "Deng", // 登
   "Du", // 度
   "Dun", // 惇
   "Fan", // 范
   "Fang", // 芳
   "Fei", // 飞
   "Feng", // 丰
   "Feng", // 封
   "Fu", // 馥
   "Fu", // 辅
   "Gai", // 盖
   "Gang", // 刚
   "Gong", // 恭
   "Gong", // 宫
   "Guang", // 光
   "He", // 合
   "He", // 和
   "Hong", // 洪
   "Hong", // 宏
   "Huan", // 桓
   "Huang", // 晃
   "Hui", // 会
   "Ji", // 绩
   "Ji", // 纪
   "Jia", // 嘉
   "Jian", // 坚
   "Jian", // 简
   "Jiang", // 奖
   "Jin", // 瑾
   "Jin", // 进
   "Jing", // 敬
   "Jing", // 景
   "Jiu", // 就
   "Ju", // 据
   "Jun", // 俊
   "Jun", // 钧
   "Kai", // 楷
   "Kang", // 康
   "Lang", // 朗
   "Li", // 礼
   "Liang", // 亮
   "Liang", // 良
   "Liao", // 辽
   "Lie", // 烈
   "Lin", // 林
   "Ling", // 灵
   "Lu", // 鲁
   "Meng", // 蒙
   "Miao", // 邈
   "Min", // 敏
   "Ning", // 宁
   "Pei", // 配
   "Pi", // 丕
   "Ping", // 平
   "Pu", // 普
   "Qian", // 谦
   "Qin", // 钦
   "Qing", // 庆
   "Qiu", // 丘
   "Quan", // 权
   "Ren", // 仁
   "Rong", // 融
   "Rou", // 柔
   "Rui", // 睿
   "Shao", // 绍
   "Sheng", // 盛
   "Shi", // 师
   "Shou", // 寿
   "Shu", // 舒
   "Shu", // 术
   "Shun", // 顺
   "Song", // 松
   "Su", // 肃
   "Sui", // 遂
   "Tai", // 泰
   "Teng", // 腾
   "Tong", // 统
   "Tong", // 通
   "Wan", // 琬
   "Wei", // 维
   "Wei", // 韦
   "Wen", // 温
   "Wu", // 武
   "Xi", // 熙
   "Xian", // 宪
   "Xiang", // 详
   "Xin", // 歆
   "Xiu", // 修
   "Xu", // 诩
   "Xuan", // 玄
   "Xun", // 逊
   "Yan", // 延
   "Yan", // 严
   "Yang", // 杨
   "Yao", // 繇
   "Ye", // 晔
   "Yi", // 懿
   "Yi", // 仪
   "Yi", // 义
   "Yin", // 胤
   "Ying", // 英
   "Yong", // 雍
   "You", // 攸
   "Yu", // 瑜
   "Yu", // 彧
   "Yu", // 羽
   "Yuan", // 渊
   "Yue", // 悦
   "Yun", // 云
   "Zan", // 瓒
   "Zhang", // 璋
   "Zhao", // 昭
   "Zhen", // 震
   "Zhen", // 真
   "Zheng", // 正
   "Zhi", // 芝
   "Zhi", // 植
   "Zhong", // 忠
   "Zhou", // 胄
   "Zhu", // 竺
];

const FemaleGivenNames = [
   "Ai", // 爱
   "An", // 安
   "Bai", // 白
   "Cai", // 采
   "E", // 娥
   "Fang", // 芳
   "Fen", // 芬
   "Fu", // 福
   "Gui", // 桂
   "Hua", // 华
   "Hui", // 惠
   "Hui", // 慧
   "Jie", // 节
   "Jing", // 静
   "Lan", // 兰
   "Li", // 丽
   "Lian", // 廉
   "Ling", // 灵
   "Min", // 敏
   "Ning", // 宁
   "Qiong", // 琼
   "Rong", // 荣
   "Rong", // 容
   "Rou", // 柔
   "Shu", // 淑
   "Shun", // 顺
   "Wan", // 婉
   "Xian", // 娴
   "Xiu", // 秀
   "Xuan", // 宣
   "Ya", // 雅
   "Yan", // 琰
   "Yan", // 艳
   "Yao", // 瑶
   "Yi", // 仪
   "Ying", // 英
   "Ying", // 瑛
   "Yu", // 玉
   "Yuan", // 媛
   "Yue", // 月
   "Zhen", // 贞
   "Zhen", // 珍
   "Zhi", // 芝
   "Zhu", // 珠
];

function randomMaleName(familyName?: string, random = Math.random): [string, string] {
   return [familyName ?? randOne(FamilyNames, random), randOne(MaleGivenNames, random)];
}

function randomFemaleName(familyName?: string, random = Math.random): [string, string] {
   return [familyName ?? randOne(FamilyNames, random), randOne(FemaleGivenNames, random)];
}

function getFamilyName(name: string[]): string {
   return name[0];
}

export const ChineseNameGenerator = {
   getFamilyName,
   randomName(gender, familyName, random) {
      return gender === "male" ? randomMaleName(familyName, random) : randomFemaleName(familyName, random);
   },
} satisfies INameGenerator;
