name: Unit Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-script:
    runs-on: [self-hosted]
    steps:
      - run: |
          git checkout .
          git pull --rebase
          git submodule update --recursive --remote --init
          pnpm install
          pnpm run build
        working-directory: /home/insraq/Restitutor
